#!/bin/bash
cd ${0%/*} || exit 1    		    		# Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Fluid participant

# Run this script in one terminal and the "runFluid2" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# Run this script with "-parallel" for parallel simulations

# The script "Allclean" cleans-up the result and log files.

# 1 for true, 0 for false
parallel=0
if [ "$1" = "-parallel" ]; then
    parallel=1
fi

echo "Preparing and running the Fluid1 participant..."

# Prepare
if [ $parallel -eq 1 ]; then
    ln -s -f precice-config_parallel.xml precice-config.xml
else
    ln -s -f precice-config_serial.xml precice-config.xml
fi

rm -rfv Fluid1/0/
cp -r Fluid1/0.orig/ Fluid1/0/
blockMesh -case Fluid1
checkMesh -case Fluid1

# Run
cd Fluid1
    solver=$(getApplication)
cd ..
if [ $parallel -eq 1 ]; then
    decomposePar -case Fluid1
    cd Fluid1
        nproc=$(getNumberOfProcessors)
    cd ..
    mpirun -np $nproc $solver -parallel -case Fluid1
    reconstructPar -case Fluid1
else
    $solver -case Fluid1
fi

#foamToVTK -case Fluid1

# Workaround for issue #26
./removeObsoleteFolders.sh
