#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning..."

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Participant 1: Fluid
Participant1="Fluid"
cd ${Participant1}
    # Clean the case
    cleanCase
    # Create an empty .foam file for ParaView
    # Note: ".foam" triggers the native OpenFOAM reader of ParaView.
    # Change to ".OpenFOAM" to use the OpenFOAM reader provided with OpenFOAM.
    touch ${Participant1}.foam
cd ..
# Remove the log file
rm -f ${Participant1}.log

# Participant 2: Solid
Participant2="Solid"
cd ${Participant2}
    # Clean the case
    cleanCase
    # Create an empty .foam file for ParaView
    # Note: ".foam" triggers the native OpenFOAM reader of ParaView.
    # Change to ".OpenFOAM" to use the OpenFOAM reader provided with OpenFOAM.
    touch ${Participant2}.foam
cd ..
rm -f ${Participant2}.log

# Remove the preCICE-related log files
rm -f convergence-*.log convergence-*.txt
rm -f EventTimings-*.log EventTimings-*.txt
rm -f iterations-*.log iterations-*.txt

echo "Cleaning complete!"
#------------------------------------------------------------------------------
