#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Check if an OpenFOAM environment is available
if [ -z "${WM_PROJECT_VERSION}" ]; then
    echo "It looks like no OpenFOAM environment is available. Have you loaded the OpenFOAM etc/bashrc file?"
    echo "Cleaning failed."
    exit 1
fi

# Cleanup all the WMake directories
wclean && echo "Cleaning complete!"

# Delete the log files
rm -f wmake.log ldd.log
