#!/bin/bash

cat precice-config.xml | precice-config-visualizer --data-access full --communicator hide --cplschemes hide --data-exchange full  | dot -Tpdf > precice-config.pdf
xdg-open precice-config.pdf
