#!/bin/bash
type=5
output="SWEoutput_of-swe_subcritical/swe_solver_of-swe_subcritical"
sizeX=20
sizeY=40
build=~/thesis/both/tutorials/FF/dambreak/of-swe_subcritical/SWE_gnu.py
solverNum=1
. ./SWE_solver/run.sh
