#!/bin/bash
type=3
output="SWEoutput_swe-of_subcritical/swe_solver_swe-of_subcritical"
sizeX=20
sizeY=20
build=~/thesis/both/tutorials/FF/dambreak/swe-of_subcritical/SWE_gnu.py
solverNum=1
. ./SWE_solver/run.sh
