#!/bin/bash
cd ${0%/*} || exit 1    		    		# Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Fluid participant

# Run this script in one terminal and the "runFluid2" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# Run this script with "-parallel" for parallel simulations

# The script "Allclean" cleans-up the result and log files.

# 1 for true, 0 for false
parallel=0
if [ "$1" = "-parallel" ]; then
    parallel=1
fi

echo "Preparing and running the interFoam_monolithic_subcritical participant..."

# Prepare
rm -rfv interFoam_monolithic_subcritical/0/
cp -r interFoam_monolithic_subcritical/0.orig/ interFoam_monolithic_subcritical/0/
blockMesh -case interFoam_monolithic_subcritical
checkMesh -case interFoam_monolithic_subcritical
setFields -case interFoam_monolithic_subcritical

# Run
cd interFoam_monolithic_subcritical
    solver=$(getApplication)
cd ..
if [ $parallel -eq 1 ]; then
    decomposePar -case interFoam_monolithic_subcritical
    cd interFoam_monolithic_subcritical
        nproc=$(getNumberOfProcessors)
    cd ..
    mpirun -np $nproc $solver -parallel -case interFoam_monolithic_subcritical
    reconstructPar -case interFoam_monolithic_subcritical
else
    $solver -case interFoam_monolithic_subcritical
fi

#foamToVTK -case interFoam_monolithic_subcritical

# Workaround for issue #26
./removeObsoleteFolders.sh
