#!/bin/bash
cd ${0%/*} || exit 1    		    		# Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Fluid participant

# Run this script in one terminal and the "runFluid1" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# Run this script with "-parallel" for parallel simulations

# The script "Allclean" cleans-up the result and log files.

# 1 for true, 0 for false
parallel=0
if [ "$1" = "-parallel" ]; then
    parallel=1
fi

echo "Preparing and running the IF_Right participant..."

# Prepare
rm -rfv IF_Right/0/
cp -r IF_Right/0.orig/ IF_Right/0/
blockMesh -case IF_Right
checkMesh -case IF_Right
setFields -case IF_Right


# Run
cd IF_Right
	solver=$(getApplication)
cd ..
if [ $parallel -eq 1 ]; then
    decomposePar -force -case IF_Right
    cd IF_Right
            nproc=$(getNumberOfProcessors)
    cd ..
    mpirun -np $nproc $solver -parallel -case IF_Right
    reconstructPar -case IF_Right
else
    $solver -case IF_Right
fi
