#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning..."

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Participant 1: Fluid
Participant1="Fluid"
cd ${Participant1}
    # Clean the case
    cleanCase
    # Create an empty .foam file for ParaView
    # Note: ".foam" triggers the native OpenFOAM reader of ParaView.
    # Change to ".OpenFOAM" to use the OpenFOAM reader provided with OpenFOAM.
    touch ${Participant1}.foam
cd ..
# Remove the log files
rm -f ${Participant1}_blockMesh.log
rm -f ${Participant1}_checkMesh.log
rm -f ${Participant1}_decomposePar.log
rm -f ${Participant1}.log
rm -f ${Participant1}_reconstructPar.log

# Participant 2: Solid
Participant2="Solid"
cd ${Participant2}
    # Clean the case
    cleanCase
    # Create an empty .foam file for ParaView
    # Note: ".foam" triggers the native OpenFOAM reader of ParaView.
    # Change to ".OpenFOAM" to use the OpenFOAM reader provided with OpenFOAM.
    touch ${Participant2}.foam
cd ..
# Remove the log files
rm -f ${Participant2}_blockMesh.log
rm -f ${Participant2}_checkMesh.log
rm -f ${Participant2}_decomposePar.log
rm -f ${Participant2}.log
rm -f ${Participant2}_reconstructPar.log

# Remove the preCICE-related log files
echo "Deleting the preCICE log files..."
rm -f \
    precice-*.log \
    precice-*.json
    
# Output files for preCICE versions before 1.2:
rm -f \
    iterations-${Participant1}.txt iterations-${Participant2}.txt \
    convergence-${Participant1}.txt convergence-${Participant2}.txt \
    Events-${Participant1}.log Events-${Participant2}.log \
    EventTimings-${Participant1}.log EventTimings-${Participant2}.log

rm -f .${Participant1}-${Participant2}.address

echo "Cleaning complete!"
#------------------------------------------------------------------------------
