#!/bin/bash

# Solid participant

# Run this script in one terminal and the "runFluid" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# The script "Allclean" cleans-up the result and log files.

# Use the precice-config for the serial run
ln -s -f nearest-projection-setup.xml precice-config.xml

# Prepare
blockMesh -case Solid

# Run
laplacianFoam -case Solid
