participant: Fluid

precice-config-file: precice-config.xml

interfaces:
- mesh: Fluid-Mesh
  locations: faceTriangles # optional, defaults to faceCenters
  patches:
  - interface
  write-data: Temperature
  read-data: Heat-Flux

CHTenabled: true
