participant: Fluid

precice-config-file: precice-config.xml

interfaces:
- mesh: Fluid-Mesh-Centers
  locations: faceCenters # optional, defaults to faceCenters
  provideMeshConnectivity: false
  patches:
  - interface
  read-data: Heat-Flux
- mesh: Fluid-Mesh-Nodes
  locations: faceNodes # optional, defaults to faceCenters
  provideMeshConnectivity: true  
  patches:
  - interface
  write-data: Temperature

CHTenabled: true
