participant: Solid

precice-config-file: precice-config.xml

interfaces:
- mesh: Solid-Mesh-Centers
  locations: faceCenters   # optional, defaults to faceCenters
  patches:
  - interface  #right_interface
  read-data: Temperature
- mesh: Solid-Mesh-Nodes
  locations: faceNodes   # optional, defaults to faceCenters
  patches:
  - interface  #right_interface
  write-data: Heat-Flux

CHTenabled: true
provideMeshConnectivity: true 
