#!/bin/bash
type=1
output="SWEoutput_swe-swe_subcritical/swe_solver_swe-swe_subcritical_Left"
sizeX=40
sizeY=40
build=~/thesis/both/tutorials/FF/dambreak/swe-swe_subcritical/SWE_gnu.py
solverNum=1
. ./SWE_solver/run.sh
