name: Build with OpenFOAM 8
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup caches
      uses: actions/cache@v2
      id: cache-id
      with:
        path: ${{ runner.temp }}/cache-directory
        key: ${{ runner.os }}-cache-dependencies-openfoam8-v1.0
    - name: Install dependencies (considering cache)
      uses: airvzxf/cache-anything-new-action@v1.0.1
      with:
        script: 'install-dependencies-openfoam8.sh'
        is_cached: ${{ steps.cache-id.outputs.cache-hit }}
        cache: ${{ runner.temp }}/cache-directory
        snapshot: '/'
        exclude: '/boot /data /dev /mnt /proc /run /sys'
    - name: Rebase version-specific branch on ref
      run: git checkout OpenFOAM8 && git rebase ${GITHUB_REF##*/}
    - name: Build OpenFOAM-preCICE adapter
      run: . /opt/openfoam8/etc/bashrc && ./Allwmake
