name: Custom build (triggered manually) # Unfortunately, we cannot modify the name: https://github.community/t/github-actions-dynamic-name-of-the-workflow-with-workflow-dispatch/150327
on:
  workflow_dispatch:
    inputs:
      branchAdapter:
        description: 'Branch of the OpenFOAM adapter to build'
        default: 'develop'
        required: true
      versionOpenFOAM:
        description: 'Version of OpenFOAM to build with'
        required: true
        type: choice
        options:
          - OpenFOAMv2112
          - OpenFOAMv2106
          - OpenFOAMv2012
          - OpenFOAMv2006
          - OpenFOAMv1912
          - OpenFOAM9
          - OpenFOAM8
          - OpenFOAM7
          # We don't have precompiled packages for older versions on this Ubuntu version
      versionpreCICE:
        description: 'Released version of preCICE to build with'
        default: '2.3.0'
        required: true
      runTutorialHeatedPlate:
        description: Run tutorial flow-over-heated-plate
        type: boolean
        default: true
        required: true
      runTutorialQuickstart:
        description: Run tutorial quickstart
        type: boolean
        default: true
        requird: true
      branchTutorials:
        description: 'Branch of the tutorials to use'
        default: 'master'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Report log
      run: |
        echo "Initiated by: ${{ github.actor }}"
        echo "Adapter branch: ${{ github.event.inputs.branchAdapter }}"
        echo "OpenFOAM version: ${{ github.event.inputs.versionOpenFOAM }}"
        echo "preCICE version: ${{ github.event.inputs.versionpreCICE }}"
        echo "Run tutorial flow-over-heated-plate: ${{ github.event.inputs.runTutorialHeatedPlate }}"
        echo "Run tutorial quickstart: ${{ github.event.inputs.runTutorialQuickstart }}"
        echo "Tutorials branch: ${{ github.event.inputs.branchTutorials }}"
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branchAdapter }}
    - name: Install OpenFOAM (no cache)
      id: installOpenFOAM
      run: |
        case "${{ github.event.inputs.versionOpenFOAM }}" in
          OpenFOAMv2112)
            wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
            sudo apt-get install openfoam2112-dev
            echo "::set-output name=openfoam_exec::/usr/bin/openfoam2112";;
          OpenFOAMv2106)
            wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
            sudo apt-get install openfoam2106-dev
            echo "::set-output name=openfoam_exec::/usr/bin/openfoam2106";;
          OpenFOAMv2012)
            wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
            sudo apt-get install openfoam2012-dev
            echo "::set-output name=openfoam_exec::/usr/bin/openfoam2012";;
          OpenFOAMv2006)
            wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
            sudo apt-get install openfoam2006-dev
            echo "::set-output name=openfoam_exec::/usr/bin/openfoam2006";;
          OpenFOAMv1912)
            wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
            sudo apt-get install openfoam1912-dev
            echo "::set-output name=openfoam_exec::/usr/bin/openfoam1912";;
          OpenFOAM7)
            sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
            sudo add-apt-repository http://dl.openfoam.org/ubuntu
            sudo apt-get update
            sudo apt-get -y install openfoam7
            echo "::set-output name=openfoam_exec::. /opt/openfoam7/etc/bashrc &&";;
          OpenFOAM8)
            sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
            sudo add-apt-repository http://dl.openfoam.org/ubuntu
            sudo apt-get update
            sudo apt-get -y install openfoam8
            echo "::set-output name=openfoam_exec::. /opt/openfoam8/etc/bashrc &&";;
          OpenFOAM9)
            sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
            sudo add-apt-repository http://dl.openfoam.org/ubuntu
            sudo apt-get update
            sudo apt-get -y install openfoam9
            echo "::set-output name=openfoam_exec::. /opt/openfoam9/etc/bashrc &&";;
          *)
            echo "I cannot find ${{ github.event.inputs.branchAdapter }} in my known options."
            exit 1;;
        esac
    - name: Install preCICE (no cache)
      run: |
        wget "https://github.com/precice/precice/releases/download/v${{ github.event.inputs.versionpreCICE }}/libprecice2_${{ github.event.inputs.versionpreCICE }}_focal.deb"
        sudo apt install "./libprecice2_${{ github.event.inputs.versionpreCICE }}_focal.deb"
    - name: Build OpenFOAM-preCICE adapter
      run: |
          ${{steps.installOpenFOAM.outputs.openfoam_exec}} ./Allwmake
    - name: Run tutorial flow-over-heated-plate
      run: |
        if [ ${{ github.event.inputs.runTutorialHeatedPlate }} ]
        then
          git clone https://github.com/precice/tutorials.git --branch ${{ github.event.inputs.branchTutorials }} && ls && cd tutorials
          cd flow-over-heated-plate/fluid-openfoam
          ${{steps.installOpenFOAM.outputs.openfoam_exec}} ./run.sh &
          PIDfluid=$!
          cd ../solid-openfoam
          ${{steps.installOpenFOAM.outputs.openfoam_exec}} ./run.sh
          wait $PIDfluid
          cd ../.. && pwd && ls
        fi
    - name: Run tutorial quickstart
      run: |
        pwd && ls
        if [ ${{ github.event.inputs.runTutorialQuickstart }} ]
        then
          cd quickstart/fluid-openfoam
          ${{steps.installOpenFOAM.outputs.openfoam_exec}} ./run.sh &
          PIDfluid=$!
          cd ../solid-cpp
          cmake . && make && ./run.sh
          wait $PIDfluid
          cd ../..
        fi
