name: Build with OpenFOAM 8
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install OpenFOAM (no cache)
      run: |
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository http://dl.openfoam.org/ubuntu
        sudo apt-get update
        sudo apt-get -y install openfoam8
    - name: Install preCICE (no cache)
      run: |
        wget https://github.com/precice/precice/releases/download/v2.3.0/libprecice2_2.3.0_focal.deb
        sudo apt install ./libprecice2_2.3.0_focal.deb
    - name: Build OpenFOAM-preCICE adapter
      run: . /opt/openfoam8/etc/bashrc && ./Allwmake
