name: Custom build
on:
  workflow_dispatch:
    inputs:
      branchAdapter:
        description: 'Branch of the OpenFOAM adapter to build'
        default: 'develop'
        required: true
      versionOpenFOAM:
        description: 'Version of OpenFOAM to build with'
        required: true
        type: choice
        options:
          - OpenFOAM7
          - OpenFOAM8

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branchAdapter }}
    - name: Install OpenFOAM (no cache)
      run: |
        case "${{ github.event.inputs.versionOpenFOAM }}" in
          OpenFOAM4)
            echo "We don't have precompiled OpenFOAM 4 packages on Ubuntu 20.04."
            exit 1;;
          OpenFOAM5)
            echo "We don't have precompiled OpenFOAM 5 packages on Ubuntu 20.04."
            exit 1;;
          OpenFOAM6)
            echo "We don't have precompiled OpenFOAM 5 packages on Ubuntu 20.04."
            exit 1;;
          OpenFOAM7)
            sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
            sudo add-apt-repository http://dl.openfoam.org/ubuntu
            sudo apt-get update
            sudo apt-get -y install openfoam7;;
          OpenFOAM8)
            sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
            sudo add-apt-repository http://dl.openfoam.org/ubuntu
            sudo apt-get update
            sudo apt-get -y install openfoam8;;
          OpenFOAM9)
            sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
            sudo add-apt-repository http://dl.openfoam.org/ubuntu
            sudo apt-get update
            sudo apt-get -y install openfoam9;;
          *)
            echo "I cannot find ${{ github.event.inputs.branchAdapter }} in my known options."
            exit 1;;
        esac
    - name: Install preCICE (no cache)
      run: |
        wget https://github.com/precice/precice/releases/download/v2.3.0/libprecice2_2.3.0_focal.deb
        sudo apt install ./libprecice2_2.3.0_focal.deb
    - name: Build OpenFOAM-preCICE adapter
      run: |
        case "${{ github.event.inputs.versionOpenFOAM }}" in
          OpenFOAM7)
            . /opt/openfoam8/etc/bashrc && ./Allwmake;;
          OpenFOAM8)
            . /opt/openfoam8/etc/bashrc && ./Allwmake;;
          OpenFOAM9)
            . /opt/openfoam9/etc/bashrc && ./Allwmake;;
        esac
