name: Check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Lint shell scripts (shellcheck)
        uses: ludeeus/action-shellcheck@master
      - name: Lint markdown files (mdl)
        uses: actionshub/markdownlint@main
