name: Lint docs
on: [push, pull_request]
jobs:
  check_md:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Lint markdown files (markdownlint)
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: '.'
          ignore: changelog-entries
