name: Lint scripts
on: [push, pull_request]
jobs:
  check_shell:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Lint shell scripts (shellcheck)
        uses: ludeeus/action-shellcheck@master
