name: System tests

on:
  pull_request:
    types: [labeled]

jobs:
  gather-refs:
    if: ${{ github.event.label.name == 'trigger-system-tests' }}
    runs-on: ubuntu-latest
    outputs:
      refprecice: ${{ steps.refprecice.outputs.shorthash }}
    steps:
      - id: refprecice
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: precice
          repo: precice
          branch: develop


  test-job:
    if: ${{ github.event.label.name == 'trigger-system-tests' }}
    needs: gather-refs
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.gather-refs.outputs.refprecice }}" >> $GITHUB_OUTPUT

  trigger-system-tests:
    if: ${{ github.event.label.name == 'trigger-system-tests' }}
    needs: gather-refs
    uses: precice/tutorials/.github/workflows/run_testsuite_workflow.yml@develop
    with:
      suites: openfoam_adapter_pr
      build_args: TUTORIALS_REF:develop,PRECICE_REF:${{ needs.gather-refs.outputs.refprecice }},OPENFOAM_EXECUTABLE:openfoam2306,OPENFOAM_ADAPTER_REF:${{ github.event.pull_request.head.sha }}
      systests_branch: develop
      loglevel: "DEBUG"
