name: System tests

on:
  pull_request:
    types: [labeled]

jobs:
  run-system-tests:
    if: ${{ github.event.label.name == 'trigger-system-tests' }}
    uses: precice/tutorials/.github/workflows/system-tests.yml@develop
    with:
      suites: openfoam-adapter
      build_args: OPENFOAM_EXECUTABLE:openfoam2512,OPENFOAM_ADAPTER_PR:${{ github.event.number }},OPENFOAM_ADAPTER_REF:${{ github.event.pull_request.head.sha }}
