#!/bin/bash
cd ${0%/*} || exit 1    		    		# Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Fluid participant

# Run this script in one terminal and the "runFluid2" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# Run this script with "-parallel" for parallel simulations

# The script "Allclean" cleans-up the result and log files.

# 1 for true, 0 for false
parallel=0
if [ "$1" = "-parallel" ]; then
    parallel=1
fi

echo "Preparing and running the IF_Left participant..."

# Prepare
rm -rfv IF_Left/0/
cp -r IF_Left/0.orig/ IF_Left/0/
blockMesh -case IF_Left
checkMesh -case IF_Left
setFields -case IF_Left

# Run
cd IF_Left
    solver=$(getApplication)
cd ..
if [ $parallel -eq 1 ]; then
    decomposePar -case IF_Left
    cd IF_Left
        nproc=$(getNumberOfProcessors)
    cd ..
    mpirun -np $nproc $solver -parallel -case IF_Left
    reconstructPar -case IF_Left
else
    $solver -case IF_Left
fi

#foamToVTK -case IF_Left

# Workaround for issue #26
./removeObsoleteFolders.sh
